# Generated by Django 5.0.6 on 2024-06-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxapp', '0003_booking_clientreview_payment_delete_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.IntegerField()),
                ('booking_date', models.DateField()),
                ('event_name', models.CharField(max_length=100)),
                ('event_location', models.CharField(max_length=255)),
                ('event_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_details', models.TextField()),
            ],
        ),
    ]
