# Generated by Django 5.0.6 on 2024-06-14 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxapp', '0007_bookingrequest_delete_bookingform_alter_artist_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voxapp.artistprofile'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='pricing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Default Pricing'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_info', to='voxapp.artistprofile'),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
