# Generated by Django 5.0.6 on 2024-06-15 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxapp', '0009_alter_song_artist_alter_portfoliopicture_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voxapp.profile'),
        ),
        migrations.AlterField(
            model_name='gigrequest',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voxapp.profile'),
        ),
        migrations.AlterField(
            model_name='recommendedgig',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voxapp.profile'),
        ),
    ]
