# Generated by Django 5.0.6 on 2024-06-15 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxapp', '0010_alter_gig_artist_alter_gigrequest_artist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedgig',
            name='artist',
        ),
        migrations.AlterModelOptions(
            name='gigrequest',
            options={'verbose_name': 'Gig Request', 'verbose_name_plural': 'Gig Requests'},
        ),
        migrations.RenameField(
            model_name='gigrequest',
            old_name='date',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='gigrequest',
            old_name='description',
            new_name='event_description',
        ),
        migrations.RenameField(
            model_name='gigrequest',
            old_name='time',
            new_name='event_time',
        ),
        migrations.RemoveField(
            model_name='gigrequest',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='gigrequest',
            name='city',
        ),
        migrations.RemoveField(
            model_name='gigrequest',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='gigrequest',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='gigrequest',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='gigrequest',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='gigrequest',
            name='state',
        ),
        migrations.RemoveField(
            model_name='gigrequest',
            name='venue',
        ),
        migrations.AddField(
            model_name='gigrequest',
            name='event_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gigrequest',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gigrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AcceptedGig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_location', models.CharField(blank=True, max_length=255, null=True)),
                ('event_description', models.TextField()),
                ('client_username', models.CharField(blank=True, max_length=150, null=True)),
                ('client_email', models.EmailField(max_length=254)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voxapp.profile')),
            ],
            options={
                'verbose_name': 'Accepted Gig',
                'verbose_name_plural': 'Accepted Gigs',
            },
        ),
        migrations.CreateModel(
            name='CanceledGig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_location', models.CharField(blank=True, max_length=255, null=True)),
                ('event_description', models.TextField()),
                ('client_username', models.CharField(blank=True, max_length=150, null=True)),
                ('client_email', models.EmailField(max_length=254)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voxapp.profile')),
            ],
            options={
                'verbose_name': 'Canceled Gig',
                'verbose_name_plural': 'Canceled Gigs',
            },
        ),
        migrations.DeleteModel(
            name='Gig',
        ),
        migrations.DeleteModel(
            name='RecommendedGig',
        ),
    ]
