# Generated by Django 5.0.6 on 2024-06-15 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxapp', '0011_remove_recommendedgig_artist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceptedgig',
            options={},
        ),
        migrations.AlterModelOptions(
            name='canceledgig',
            options={},
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='standard_price',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist_name',
        ),
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.AddField(
            model_name='pricing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='gigrequest',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voxapp.profile'),
        ),
        migrations.AlterField(
            model_name='gigrequest',
            name='event_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voxapp.profile'),
        ),
    ]
