# Generated by Django 5.0.6 on 2024-06-15 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voxapp', '0012_alter_acceptedgig_options_alter_canceledgig_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pricing',
            new_name='Price',
        ),
        migrations.AlterField(
            model_name='price',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voxapp.profile'),
        ),
    ]
