# Generated by Django 5.0.6 on 2024-06-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voxapp', '0014_gigrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigrequest',
            name='status',
        ),
    ]
