# Generated by Django 5.0.6 on 2024-06-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voxapp', '0018_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GigRequest',
        ),
    ]
